name: Release

on:
  create:
    branches: 
      - release/**

defaults:
  run:
    shell: pwsh
    
env:
  DOTNET_VERSION: 8.0.300
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace}}/nuget
  
jobs:
  create_nuget:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
    - name: Define global.json
      run: dotnet new globaljson --sdk-version ${{ env.DOTNET_VERSION }}    
    - run: dotnet pack --configuration Release --output ${{ env.NuGetDirectory }}
    - uses: actions/upload-artifact@v4
      with:
        name: nuget
        if-no-files-found: error
        retention-days: 7
        path: ${{ env.NuGetDirectory }}/*.nupkg

  deploy:
    # Publish only when creating a release
    if: startsWith(github.ref, 'refs/heads/release')
    runs-on: ubuntu-latest
    needs: [ create_nuget ]
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: nuget
        path: ${{ env.NuGetDirectory }}
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
    - name: Define global.json
      run: dotnet new globaljson --sdk-version ${{ env.DOTNET_VERSION }}    
    - name: Publish NuGet package
      run: |
        foreach($file in (Get-ChildItem "${{ env.NuGetDirectory }}" -Recurse -Include *.nupkg)) {
            dotnet nuget push $file --api-key "${{ secrets.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json
        }
